NAME = ft_display_file

CC = cc
CFLAGS = -Wall -Wextra -Werror

SRC = ft_display_file.c

all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)